// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGWChXOExzRYgnwVdosaWQGRay9__5xKg',
    appId: '1:854366573421:web:ca97d7f787092ea3114064',
    messagingSenderId: '854366573421',
    projectId: 'tahina-2abc2',
    authDomain: 'tahina-2abc2.firebaseapp.com',
    storageBucket: 'tahina-2abc2.firebasestorage.app',
    measurementId: 'G-GDV3MKBGPS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYMfzaHgulAwlQX2NCfYa6yHvrcoB66Ts',
    appId: '1:854366573421:android:5ad63db57ff3f171114064',
    messagingSenderId: '854366573421',
    projectId: 'tahina-2abc2',
    storageBucket: 'tahina-2abc2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe-DvemRwW5shK_wT7D3AJP_Q9duHyc64',
    appId: '1:854366573421:ios:059f996936d26721114064',
    messagingSenderId: '854366573421',
    projectId: 'tahina-2abc2',
    storageBucket: 'tahina-2abc2.firebasestorage.app',
    iosBundleId: 'com.snabel.altahina.customer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe-DvemRwW5shK_wT7D3AJP_Q9duHyc64',
    appId: '1:854366573421:ios:059f996936d26721114064',
    messagingSenderId: '854366573421',
    projectId: 'tahina-2abc2',
    storageBucket: 'tahina-2abc2.firebasestorage.app',
    iosBundleId: 'com.snabel.altahina.customer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGWChXOExzRYgnwVdosaWQGRay9__5xKg',
    appId: '1:854366573421:web:1069b1be00fa5758114064',
    messagingSenderId: '854366573421',
    projectId: 'tahina-2abc2',
    authDomain: 'tahina-2abc2.firebaseapp.com',
    storageBucket: 'tahina-2abc2.firebasestorage.app',
    measurementId: 'G-YHMJWWQDNB',
  );

}